[package]
name = "dori-client"
description = "Dori client implementation."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dori-lib = { path = "../lib" }
tora = "0.1.5"
serde = { version = "1.0.193", features = ["derive"] }
